import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';

const html=fs.readFileSync(new URL('../合掌网页版-正式版本存档/合掌网页版v2.5.8.1.html',import.meta.url),'utf8');
const script=html.slice(html.indexOf('<script>')+8,html.lastIndexOf('</script>'));
const node=()=>({innerHTML:'',textContent:'',value:'',open:false,children:[],style:{setProperty(){}},classList:{add(){},remove(){},toggle(){}},addEventListener(){},removeEventListener(){},showModal(){this.open=true;},close(){this.open=false;},querySelectorAll(){return[];},querySelector(){return node();}});
function game(){
  const nodes=new Map(),document={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},querySelectorAll(){return[];},querySelector(){return node();},documentElement:node(),body:node(),addEventListener(){}};
  const context=vm.createContext({console,document,navigator:{},localStorage:{getItem(){return null;},setItem(){}},structuredClone,setTimeout(){return 1;},clearTimeout(){},setInterval(){return 1;},clearInterval(){},URL,Blob,performance:{now:()=>0},Math:Object.create(Math)});
  vm.runInContext(script.slice(0,script.lastIndexOf('\ninit();')),context);
  vm.runInContext(`render=()=>{};renderMp=()=>{};showToast=()=>{};showMonsterRpsResult=async()=>{};chooseUse258=async()=>true;chooseMpOption=async()=>null;Math.random=()=>.9;`,context);
  return code=>vm.runInContext(code,context);
}
function solo(g,p='generalist',a='none'){g(`data.settings.skillsEnabled=true;data.settings.playerSkill=${JSON.stringify(p)};data.settings.aiSkill=${JSON.stringify(a)};state=newState();`);}
function multi(g,skills=['generalist','none']){g(`mpState={fighters:${JSON.stringify(skills)}.map((s,i)=>createMpFighter(i,i,false,s)),round:1,step:1,phase:'round-start',weaponHistory:[],log:[],fieldDeclarations:[],global:{disabledSkillTeams:new Set(),friendlyFireTeams:new Set(),multiHitTeams:new Set(),damageReductionTeams:new Map()},currentActions:new Map()};`);}

test('full script parses, 38 third-edition roles have updated stats',()=>{new vm.Script(script);const g=game();assert.equal(g('SKILL_KEYS.length'),38);assert.deepEqual(JSON.parse(g('JSON.stringify([SKILLS.reaper.hp,SKILLS.reaper.attack,SKILLS.judge.hp,SKILLS.observer.hp,SKILLS.observer.attack])')),[2,0,2,2,1]);});
test('generalist consecutive forge, interrupted forge and hit cancellation',()=>{const g=game();solo(g);g('spendAndGain("player","forge");spendAndGain("player","forge");');assert.equal(g('state.player.energy'),3);g('spendAndGain("player","guard");spendAndGain("player","forge");');assert.equal(g('state.player.energy'),4);g('spendAndGain("player","forge",false)');assert.equal(g('state.player.energy'),4);});
test('multiplayer generalist uses preceding gesture',async()=>{const g=game();multi(g);g('var c=createMultiplayerStepContext(new Map([[0,"forge"],[1,"forge"]]));commitMultiplayerActions(c);');await g('settleMultiplayerForgeAndRoundSkills(c)');g('c=createMultiplayerStepContext(new Map([[0,"forge"],[1,"forge"]]));commitMultiplayerActions(c);');await g('settleMultiplayerForgeAndRoundSkills(c)');assert.equal(g('mpState.fighters[0].energy'),3);});
test('guardian catch gains .25 and flash costs 1 in both paths',()=>{const g=game();solo(g,'guardian');g('spendAndGain("player","catch")');assert.equal(g('state.player.energy'),.25);assert.equal(g('moveCost("flash","guardian",state.player)'),1);multi(g,['guardian','none']);assert.equal(g('mpMoveCost(mpState.fighters[0],"flash")'),1);});
test('bulwark costs 2 then free until reset',()=>{const g=game();solo(g,'bulwark');assert.equal(g('moveCost("bigShield","bulwark",state.player)'),2);g('state.player.energy=2;spendAndGain("player","bigShield")');assert.equal(g('moveCost("bigShield","bulwark",state.player)'),0);multi(g,['bulwark','none']);g('mpState.fighters[0].energy=2;commitMultiplayerActions(createMultiplayerStepContext(new Map([[0,"bigShield"],[1,"guard"]])))');assert.equal(g('mpMoveCost(mpState.fighters[0],"bigShield")'),0);});
test('zero-damage and shielded reaper hits grow, blocked attacks do not',async()=>{const g=game();solo(g,'reaper','blackEmperor');await g('resolveDuelDamagePipeline(resolveWithSkills("knife","forge","reaper","blackEmperor",state.player,state.ai),"knife","forge")');assert.equal(g('state.player.attack'),1);assert.equal(g('state.player.hp'),3);assert.equal(g('state.ai.shields'),3);multi(g,['reaper','blackEmperor']);await g('resolveMpConfirmedHit(mpState.fighters[1],makeMpAttack(mpState.fighters[0],"knife"),new Map([[0,"knife"],[1,"forge"]]),[])');assert.equal(g('mpState.fighters[0].attack'),1);});
test('apprentice copies remaining charges on shielded hit, no duplicate heal',async()=>{const g=game();multi(g,['apprentice','pioneer']);g('mpState.fighters[1].activeUses.pioneer=0;');await g('hitSkills258(mpState.fighters[0],mpState.fighters[1],"knife",[],true)');assert.equal(g('mpState.fighters[0].activeUses.pioneer'),0);await g('hitSkills258(mpState.fighters[0],mpState.fighters[1],"knife",[],true)');assert.equal(g('mpState.fighters[0].hp'),2);});
test('tyrant restores at the end of the following round, not current round',()=>{const g=game();solo(g,'tyrant');g('activateTyrant258(state.player,4);restoreTyrant258(state.player,4,[])');assert.equal(g('state.player.hp'),1);g('restoreTyrant258(state.player,5,[])');assert.equal(g('state.player.hp'),3);assert.equal(g('state.player.tyrantUses'),1);});
test('sun bans selected weapon for enemy, not ally; field conflict removes ban',()=>{const g=game();multi(g,['sun','none','none']);g('mpState.fighters[2].team=0;mpState.fighters.forEach(f=>f.energy=6);registerMpField(mpState.fighters[0],"sun","小刀")');assert.equal(g('mpLegalMoves(mpState.fighters[1]).includes("knife")'),false);assert.equal(g('mpLegalMoves(mpState.fighters[2]).includes("knife")'),true);g('registerMpField(mpState.fighters[1],"night")');assert.equal(g('mpLegalMoves(mpState.fighters[1]).includes("knife")'),true);});
test('black night suppresses passive, leaves active usable, death removes seal',()=>{const g=game();multi(g,['night','tyrant']);g('mpState.fighters[1].passiveSeals=[0]');assert.equal(g('skillEnabledMp(mpState.fighters[1],"tyrant")'),false);assert.equal(g('skillEnabledMp(mpState.fighters[1],"tyrant","active")'),true);g('mpState.fighters[0].alive=false');assert.equal(g('skillEnabledMp(mpState.fighters[1],"tyrant")'),true);});
test('ascetic blocks all HP increments and loses passive under night seal',()=>{const g=game();multi(g,['ascetic','none','night']);g('gainHp258(mpState.fighters[1],1)');assert.equal(g('mpState.fighters[1].hp'),2);g('mpState.fighters[0].passiveSeals=[2];gainHp258(mpState.fighters[1],1)');assert.equal(g('mpState.fighters[1].hp'),3);});
test('ascetic optional lethal prevention is once, shield absorption does not consume it',async()=>{const g=game();multi(g,['none','ascetic']);g('mpState.fighters[1].shields=1');await g('applyMpDamage(mpState.fighters[1],{attacker:mpState.fighters[0],damage:5,key:"knife"},[])');assert.equal(g('mpState.fighters[1].asceticUses'),1);await g('applyMpDamage(mpState.fighters[1],{attacker:mpState.fighters[0],damage:5,key:"knife"},[])');assert.equal(g('mpState.fighters[1].hp'),2);assert.equal(g('mpState.fighters[1].asceticUses'),0);});
test('shadow prevents skill-death but not lethal weapon hit; RPS wins automatically',async()=>{const g=game();multi(g,['none','shadow']);await g('applyMpDamage(mpState.fighters[1],{attacker:mpState.fighters[0],damage:2},[])');await g('settleMpDeaths([])');assert.equal(g('mpState.fighters[1].hp'),1);assert.equal((await g('resolveMpMonsterDuel(mpState.fighters[1],mpState.fighters[0],mpState.fighters[0],[])')).prevented,true);await g('applyMpDamage(mpState.fighters[1],{attacker:mpState.fighters[0],damage:2,key:"knife"},[])');await g('settleMpDeaths([])');assert.equal(g('mpState.fighters[1].alive'),false);});
test('observer calm halves outgoing damage; catch adds one forge and persists rage',()=>{const g=game();multi(g,['observer','none']);assert.equal(g('makeMpAttack(mpState.fighters[0],"knife").damage'),.5);g('commitMultiplayerActions(createMultiplayerStepContext(new Map([[0,"catch"],[1,"forge"]])))');assert.equal(g('mpState.fighters[0].energy'),1);assert.equal(g('makeMpAttack(mpState.fighters[0],"knife").damage'),2);});
test('warrior pierces guard as true damage through shields',async()=>{const g=game();multi(g,['warrior','blackEmperor']);await g('resolveMpConfirmedHit(mpState.fighters[1],makeMpAttack(mpState.fighters[0],"katana"),new Map([[1,"guard"]]),[])');assert.equal(g('mpState.fighters[1].hp'),.5);assert.equal(g('mpState.fighters[1].shields'),3);});
test('keeper dragon fang hits flash in both paths',()=>{const g=game();solo(g,'secretKeeper');assert.equal(g('resolveWithSkills("dragonFang","flash","secretKeeper","none",state.player,state.ai).aiHit'),true);multi(g,['secretKeeper','none']);assert.equal(g('mpDefensePreview(mpState.fighters[1],"flash",makeMpAttack(mpState.fighters[0],"dragonFang")).blocked'),false);});
test('fisher challenge deals one damage and cancels skill without a hook',async()=>{const g=game();multi(g,['fisherman','tyrant']);g('resolveNoSkillChallenge=async()=>true');assert.equal(await g('mpActiveAllowed(mpState.fighters[1])'),false);assert.equal(g('mpState.fighters[1].hp'),2);assert.equal(g('mpState.fighters[1].alive'),true);});
test('saint shield loss stores .5 for next damage',async()=>{const g=game();multi(g,['none','saint']);await g('applyMpDamage(mpState.fighters[1],{attacker:mpState.fighters[0],damage:1,key:"knife"},[])');assert.equal(g('mpState.fighters[1].saintBonus'),.5);await g('applyMpDamage(mpState.fighters[0],{attacker:mpState.fighters[1],damage:1,key:"knife"},[])');assert.equal(g('mpState.fighters[0].hp'),.5);assert.equal(g('mpState.fighters[1].saintBonus'),0);});
test('singularity has two field uses and repeatable per-round action',()=>{const g=game();solo(g,'singularity');assert.equal(g('state.player.singularityFieldUses'),2);multi(g,['singularity','none']);assert.equal(g('mpState.fighters[0].fieldUses.singularity'),2);});
test('old exit, fish hook, rewind and shield-help controls are absent',()=>{const g=game();solo(g,'audience');assert.equal(g('availableMoveKeys("audience",state.player).includes("exit")'),false);multi(g,['fisherman','none']);assert.equal(g('getMpActiveActions(mpState.fighters[0]).some(x=>x[0]==="hook")'),false);});
test('basic mode, engine isolation and retained judgement checks',()=>{const g=game();assert.equal(g('runBasicEnergyChecks().passed'),true);assert.equal(g('runEngineIsolationChecks().passed'),true);assert.equal(g('resolveDuelCombat("knife","knife").playerHit'),false);assert.equal(g('mpShouldResist([{attacker:{team:0}},{attacker:{team:1}}],3)'),true);});
test('pioneer still replaces damage outside opening, active survives passive suppression',async()=>{const g=game();solo(g,'none','pioneer');await g('resolveDuelDamagePipeline(resolveWithSkills("knife","forge","none","pioneer",state.player,state.ai),"knife","forge")');assert.equal(g('state.ai.hp'),1);});
test('all 38 roles execute both damage pipelines without runtime errors',async()=>{const g=game();const keys=g('Array.from(SKILL_KEYS)');g('resolveNoSkillChallenge=async()=>false;resolveSoloMonsterDuel=async()=>({prevented:false});resolveMpMonsterDuel=async()=>({prevented:false});');for(const key of keys){solo(g,key);await g('resolveDuelDamagePipeline(resolveWithSkills("knife","forge",data.settings.playerSkill,"none",state.player,state.ai),"knife","forge")');multi(g,[key,'none']);await g('resolveMpConfirmedHit(mpState.fighters[1],makeMpAttack(mpState.fighters[0],"knife"),new Map([[1,"forge"]]),[])');assert.ok(Number.isFinite(g('mpState.fighters[1].hp')),key);}});
test('all 38 roles defend in both damage pipelines without runtime errors',async()=>{const g=game();const keys=g('Array.from(SKILL_KEYS)');g('resolveNoSkillChallenge=async()=>false;resolveSoloMonsterDuel=async()=>({prevented:false});resolveMpMonsterDuel=async()=>({prevented:false});');for(const key of keys){solo(g,'none',key);await g('resolveDuelDamagePipeline(resolveWithSkills("knife","forge","none",data.settings.aiSkill,state.player,state.ai),"knife","forge")');multi(g,['none',key]);await g('resolveMpConfirmedHit(mpState.fighters[1],makeMpAttack(mpState.fighters[0],"knife"),new Map([[1,"forge"]]),[])');assert.ok(Number.isFinite(g('mpState.fighters[1].hp')),key);}});
test('assassin may decline bonus and preserve its single use',async()=>{const g=game();solo(g,'assassin');g('chooseUse258=async()=>false');await g('resolveDuelDamagePipeline(resolveWithSkills("knife","forge","assassin","none",state.player,state.ai),"knife","forge")');assert.equal(g('state.ai.hp'),1);assert.equal(g('state.player.assassinUsed'),false);});
test('ascetic true-damage lethal prevention ignores body shield',async()=>{const g=game();solo(g,'sun','ascetic');g('state.player.attack=4;state.ai.shields=1');await g('resolveDuelDamagePipeline(resolveWithSkills("knife","forge","sun","ascetic",state.player,state.ai),"knife","forge")');assert.equal(g('state.ai.hp'),2);assert.equal(g('state.ai.asceticUses'),0);assert.equal(g('state.ai.shields'),1);});
test('audience only reacts to non-knife hit and retirement expires',async()=>{const g=game();multi(g,['audience','none','none']);await g('audienceMp258(mpState.fighters[0],"knife",[])');assert.equal(g('mpState.fighters[0].retreatUntil'),undefined);await g('audienceMp258(mpState.fighters[0],"katana",[])');assert.equal(g('mpState.fighters[0].retreatUntil'),2);assert.equal(g('mpState.fighters[0].hp'),1);});
test('judge fires once at round end with damage anywhere, not inside after-damage',async()=>{const g=game();multi(g,['judge','none','none']);g('var challenges=0;resolveNoSkillChallenge=async()=>{challenges++;return true;};wantsMpJudge=async()=>true;');await g('afterMpDamage(mpState.fighters[1],mpState.fighters[2],.5,[])');assert.equal(g('challenges'),0);await g('roundJudgesMp258([])');assert.equal(g('challenges'),1);assert.equal(g('mpState.fighters[0].activeUses.judge'),2);});
test('embedded rulebook matches the third-edition release rule text',()=>{const g=game();assert.equal(g('EMBEDDED_RULEBOOK_MD'),fs.readFileSync(new URL('../docs/rules/releases/合掌v2.5.8规则.md',import.meta.url),'utf8'));assert.equal(g('runRuleScenarioTests().passed'),true);});
test('basic duel attack records a complete round without skill-only state',async()=>{const g=game();g('data.settings.skillsEnabled=false;state=newState();state.player.energy=1;playTone=()=>{};startTimer=()=>{};showScoreFeedback=()=>{};');await g('settleDuelRound("knife","forge")');assert.equal(g('state.player.score'),1);assert.equal(g('state.player.energy'),0);assert.equal(g('state.log.length'),1);});
test('thief retains temporary skills between gestures, expires at round reset',()=>{const g=game();solo(g,'thief','pioneer');g('state.ai.pioneerUses=0;beginSoloThiefBorrow("player");finishSoloRoundState({player:false,ai:false},{player:0,ai:0},[],false)');assert.equal(g('state.player.pioneerUses'),0);assert.equal(g('fighterOwnsSoloSkill("thief",state.player,"pioneer")'),true);g('finishSoloRoundState({player:false,ai:false},{player:0,ai:0},[],true)');assert.equal(g('fighterOwnsSoloSkill("thief",state.player,"pioneer")'),false);});
test('retired actors cannot activate skills or submit actions',async()=>{const g=game();multi(g,['audience','none','none']);await g('audienceMp258(mpState.fighters[0],"katana",[])');assert.equal(g('mpState.fighters[0].skipped'),true);assert.equal(g('skillEnabledMp(mpState.fighters[0],"audience","active")'),false);assert.throws(()=>g('commitMultiplayerActions(createMultiplayerStepContext(new Map([[0,"forge"]])))'),/非法/);});
